//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6.AppDate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bron> bron { get; set; }
        public virtual DbSet<Carss> Carss { get; set; }
        public virtual DbSet<compl> compl { get; set; }
        public virtual DbSet<cveta> cveta { get; set; }
        public virtual DbSet<izbr> izbr { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<salonch> salonch { get; set; }
        public virtual DbSet<strana> strana { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
